repos:
  - repo: local
    hooks:
      - id: unit-tests
        name: unit tests
        entry: uv run pytest tests/unit --timeout=10
        language: system
        pass_filenames: false
      - id: e2e-tests
        name: e2e tests
        entry: uv run pytest tests/e2e --timeout=10
        language: system
        pass_filenames: false
      - id: integration-tests-ci
        name: integration tests (CI status)
        entry: bash tests/scripts/check_last_integration_ci.sh tests.yml integration-tests
        language: system
        pass_filenames: false
        stages: [pre-push]
      - id: uv-check-lock
        name: uv lock is current
        entry: uv lock --check
        language: system
        pass_filenames: false
        files: ^(pyproject\.toml|uv\.lock)$
      - id: flake8
        name: flake8
        entry: uv run flake8
        language: system
        types: [python]
