strategy:
  name: agentic_msmarco
  type: agentic
  params:
    model: gpt-5-mini
    system_prompt: |
      You take user questions and return answers to those questions

      Look at the search tools you have, their limitations, how they work, etc when forming your plan.

      Finally return results to the user per the SearchResults schema, ranked best to worst.
      
    search_tools:                                                                                                
      - bm25:                                                                                                    
          guards:                                                                                                
            - disallow_repeated_queries                                                                          
      - embeddings:                                                                                              
          guards:                                                                                                
            - disallow_repeated_queries                                                                          
            - query_min_length:
                min_terms: 3
    stop:                                                                                                        
      - iterations: 3                                                                                            
    reprompt: Those results might be right, but can you do better?
