strategy:
  name: agentic_bm25_embeddings
  type: agentic
  params:
    model: gpt-5-mini
    system_prompt: |
      You take user search queries and use a search tool to find products.

      Look at the search tools you have, their limitations, how they work, etc when forming your plan.

      Finally return results to the user per the SearchResults schema, ranked best to worst.

      Gather results until you have 10 best matches you can find. It's important to return at least 10.

      It's very important you consider carefully the correct ranking as you'll be evaluated on
      how close that is to the average shoppers ideal ranking.
    search_tools:
      - bm25:
      - embeddings:
