strategy:
  name: ecom_query_understanding_llm_multiple
  type: query_understanding
  params:
    reasoning: medium
    categorize:
      field: "category hierarchy"
      enrichment_engine:
        type: llm_multiple
        model: gpt-5-mini
        params:
          prompt: |
            Below is a search query for a furniture / homegoods store. Your job
            is to help categorize the query into one or more relevant categories

            For the given query, please generate all appropriate {field} values
            for the query to filter to zero-in on the most relevant results.

            If you're unsure, or its ambiguous, return an empty list.

            Here's the query:

            {query}
    retrieval_engine:
      base: bm25_filtered
      params:
        fields: [title^9.4, description^4]
        boost_matches: 10
